name: Makefile CI

on:
  schedule:
  - cron: "0 2 * * 1-5"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get install -y fasm

    - name: Build kernel
      run: make kernel

    - name: Build bootloader
      run: make bootloader

    - name: Build image
      run: make image

    - name: Clean build directory
      run: make clean
